version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 15
    commit-message:
      prefix: chore
      include: scope
    groups:
      patches:
        applies-to: version-updates
        update-types:
          - "patch"
        patterns:
          - "*"
      minors:
        applies-to: version-updates
        update-types:
          - "minor"
        patterns:
          - "*"
      react:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      vite:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "vite"
          - "@vitejs/*"
      eslint:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "eslint"
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "eslint-plugin-*"
      testing:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "@testing-library/*"
          - "vitest"
          - "jsdom"
          - "@vitest/*"
      majors-rest:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
      include: scope
    groups:
      actions:
        patterns:
          - "*"
