# This workflow will run tests using node and then publish a package to NPM when a tag is pushed

name: Publish wrapito to npm
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-beta*'
permissions:
  contents: write
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # 7.0.0
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm version --no-git-tag-version ${GITHUB_REF##*/}
      - name: Publish package
        run: |
          if [[ ${{ github.ref }} == *-beta* ]]; then
            npm run publish-package:beta --access public
          else
            npm run publish-package --access public
          fi
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@c9bcd8238b6f41e05561348339429d360b1c0247 #6.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 #3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: ${{ contains(github.ref, '-beta') }}